import { saveAs } from 'file-saver'
import JSZip from 'jszip'
import type { Competition } from '../types/competition'
import { formatFee, formatSourceDeadline } from './dates'
import { CATEGORY_LABELS, ELIGIBILITY_LABELS, RIGHTS_LABELS } from './labels'

export function buildSubmissionReadme(competition: Competition): string {
  const rights = RIGHTS_LABELS[competition.rightsEthics]
  const sourceFinal = formatSourceDeadline(
    competition.deadlines.final,
    competition.deadlines.timezone,
  )

  return `PRIX Submission Pack
${competition.name} (${competition.shortName})

--------------------------------------------------
WORK TITLES / 作品名
--------------------------------------------------
English title:
Chinese title / 中文作品名:

--------------------------------------------------
STATEMENT DRAFT / 阐述草稿
--------------------------------------------------
English (concept, audience, outcome):


中文阐述：


--------------------------------------------------
METADATA
--------------------------------------------------
Creator / studio:
Country:
Category: ${CATEGORY_LABELS[competition.category]}
Eligibility: ${ELIGIBILITY_LABELS[competition.eligibility]}
Year of work:
Client / unpublished:
Software / process:
AI disclosure:

--------------------------------------------------
SPEC CHECKLIST
--------------------------------------------------
[ ] Color space: ${competition.specs.colorSpace}
[ ] Formats: ${competition.specs.fileFormats.join(', ')}
[ ] Max file size: ${competition.specs.maxFileSizeMB} MB
${competition.specs.minDPI ? `[ ] Minimum ${competition.specs.minDPI} DPI` : '[ ] DPI as specified by organizer'}
[ ] No watermark: ${competition.specs.noWatermark ? 'required' : 'check organizer rules'}
${competition.specs.maxWordCount ? `[ ] Statement under ${competition.specs.maxWordCount} words` : '[ ] Statement length as specified'}
[ ] Deadline (organizer tz): ${sourceFinal}
[ ] Fee: ${formatFee(competition)}
[ ] Rights: ${rights.title}
    ${competition.rightsNotes}

--------------------------------------------------
FOLDER
--------------------------------------------------
01_HighRes_Images/     final delivery files
02_Supporting_Docs/    credits, process, statement PDF

Official entry: ${competition.officialUrl}

Generated by PRIX — Global Open-Call Workstation
`
}

export async function downloadSubmissionPack(competition: Competition) {
  const zip = new JSZip()
  zip.folder('01_HighRes_Images')
  zip.folder('02_Supporting_Docs')
  zip.file('README.txt', buildSubmissionReadme(competition))

  const blob = await zip.generateAsync({ type: 'blob' })
  saveAs(
    blob,
    `PRIX-${competition.shortName.replace(/\s+/g, '-')}-submission-pack.zip`,
  )
}
